name: advent-of-code-haskell
version: 1.0.0.0
homepage: 'https://github.com/dnsdhrj/advent-of-code-haskell'
license: BSD3
author: SSH
maintainer: dnsdhrj123@gmail.com
copyright: MIT
category: learn
extra-source-files:
  - README.md

language: GHC2021

ghc-options:
  - -O2
  - -threaded
  - -W
  - -Wno-unused-matches
  - -Wno-partial-type-signatures

dependencies:
  - algebraic-graphs
  - async
  - base
  - bytestring
  - containers
  - deepseq
  - directory
  - exceptions
  - filepath
  - hashtables
  - parsec
  - random
  - relude
  - stm
  - text
  - time
  - transformers
  - unliftio
  - unordered-containers
  - vector

default-extensions:
  - ApplicativeDo
  - DataKinds
  - DefaultSignatures
  - DeriveAnyClass
  - DerivingVia
  - FunctionalDependencies
  - GADTs
  - LambdaCase
  - MonadComprehensions
  - NoImplicitPrelude
  - OverloadedLists
  - OverloadedStrings
  - ParallelListComp
  - PartialTypeSignatures
  - RecordWildCards
  - StrictData
  - TypeFamilies
  - ViewPatterns

executables:
  aoc:
    source-dirs: src
    main: Main.hs
